In [1]:
import pandas as pd

In [2]:
import numpy as nm 

In [3]:
 print("hello")

hello


In [4]:
a =[21,11,31,234,234,1341,413]

In [5]:
a

[21, 11, 31, 234, 234, 1341, 413]

In [6]:
import numpy as np

In [7]:
arr = np.array(a)

In [8]:
arr

array([  21,   11,   31,  234,  234, 1341,  413])

In [9]:
arr2 = np.array([1,2,3,4,5])

In [10]:
arr2

array([1, 2, 3, 4, 5])

In [11]:
arr3 =[]
n = int(input("Enter soize of the array :")) 
for i in range(n):
    val = int(input("Enter nummber :")) 
    arr3.append(val) 
    
    

Enter soize of the array :1
Enter nummber :2


In [12]:
arr3

[2]

In [13]:
 arr4 = np.array(arr3)

In [14]:
arr4

array([2])

In [15]:
a= [[12 , 3234 ,34],[324,413,135], [41344,144,124]] 

In [16]:
a


[[12, 3234, 34], [324, 413, 135], [41344, 144, 124]]

In [17]:
a= np.array(a)

In [18]:
a



array([[   12,  3234,    34],
       [  324,   413,   135],
       [41344,   144,   124]])

In [19]:
a.shape


(3, 3)

In [20]:
 a = np.zeros(10)

In [21]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
a =  np.ones((10,10))

In [23]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
arr = np.eye(3,4)

In [26]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [27]:
arr=  np.eye(4,4)

In [28]:
arr= np.diag([2,3,4,5])

In [29]:
arr


array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [30]:
np.diag(arr)


array([2, 3, 4, 5])

In [31]:
num = np.random.randint(1,10,10)

In [32]:
num

array([1, 5, 4, 8, 7, 5, 2, 5, 9, 7])

In [33]:
num.count()

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [ ]:
num

In [ ]:
arr = np.random.rand(10)

In [ ]:
arr

In [ ]:
arr

In [ ]:
arr

In [ ]:
ar = np.random.rand(2,4)

In [ ]:
arr  = np.random.randn(5)

In [ ]:
arr

In [ ]:
for i in range(arr.size) :
    print(i+1 , " = " , arr[i])

## ARRAY Slicing 

 ### Reshaping the array 

In [ ]:
 a = np.arange(1,10)

In [ ]:
a


In [ ]:
 ar =a.reshape(3,3)

In [ ]:
a

In [ ]:
ar 

In [ ]:
ar.size

In [ ]:
a=  np.arange(12)

In [ ]:
a

In [ ]:
ar= a.reshape(3,4)

In [ ]:
ar

In [ ]:
ar= ar.reshape(6,2)

In [ ]:
ar 

In [ ]:
a= np.random.rand(10)

In [ ]:
a.reshape(2,5)

In [ ]:
a.reshape(1,10)

In [ ]:
a.reshape(2,-1)

In [ ]:
a.reshape(-1,5)

In [ ]:
np.random.seed(12)
np.random.randint(1,100,10) 

In [ ]:
a = np.arange(1,10)

In [ ]:
a

In [ ]:
cp = np.view(a)

In [ ]:
cp

In [ ]:
type(cp)

In [ ]:
cp= np.append([1])

In [ ]:
slicing  = a[3:7].copy()

In [ ]:
slicing

###View and Copy 

##View and Copy 

In [ ]:
a

In [ ]:
slicing[:]

In [ ]:
a[:]

In [ ]:
slicing 

In [ ]:
a = slicing[-1:-1]

In [ ]:
a

In [ ]:
type(a)

###conditional Selection

## Contional selection

In [ ]:
arr = np.arange(1,15)

In [ ]:
arr

In [ ]:
arr>10

In [ ]:
arr[arr<5]

In [ ]:
f = np.array([12,3,35,144,5,556,125,542,62,56,56,2,56,562356,5,26,62356,235])

In [ ]:
f

In [ ]:
f[f>100]

In [ ]:
 f [f==144]

In [ ]:
f[f==5]

In [ ]:
arr[arr<20] = 0

In [ ]:
arr

In [ ]:
f[f<20] =0 

In [ ]:
f


In [ ]:
f[f>20]= 100

In [ ]:
f

In [ ]:
f*3


In [ ]:
f

In [ ]:
arr+34

In [ ]:
f+=34

In [ ]:
f

In [ ]:
f**5

In [ ]:
f//5

In [ ]:
f**2

In [ ]:
f//2

In [ ]:
arr

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])

In [ ]:
arr

In [ ]:
arr.min()

## Numpy Functions

In [ ]:
arr.min()

In [ ]:
arr.max()

In [ ]:
arr.argmin()

In [ ]:
arr.argmax()

In [ ]:
np.sqrt(arr)

In [ ]:
np.sin(arr)

In [ ]:
np.cos(arr)

In [ ]:
m = np.random.randint(1,21,9).reshape(3,3)

In [ ]:
m

In [ ]:
m.sum()


In [ ]:
arr =  np.random.randint(1,21,10) 

In [ ]:
np.unique(arr)

In [ ]:
arr


In [ ]:
np.unique(arr).size

 ## numpy Stacking 

 # there are two types of stacking  ---
     1.vertical stacking 2. horizontal stacking 

In [ ]:
a1 = np.array([1,2,3,4,5])
a2= np.array([6,7,8,9,10])

In [ ]:
np.hstack((a1,a2))

##  index  Slicing 

In [ ]:
 a = np.arange(1,10).reshape(3,3)

In [ ]:
a

In [ ]:
a[1:3,1:3]

In [ ]:
a =  a.reshape(1,9)

In [ ]:
a


In [ ]:
a[4:]

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
a[4:]

In [ ]:
a[3:]

In [ ]:
a[3:1]

In [ ]:
a[-3:-1]

In [ ]:
a[1:5:2]

In [ ]:
 a = np.array([12,321,33,213,23,24,24,42,242,4,23,23]) 

In [ ]:
a[::2]

In [ ]:
a[::3]

## Fancy Indexing 

In [ ]:
a = np.arange(1,10).reshape(3,3) 

In [ ]:
a


In [ ]:
a[::2]

In [ ]:
a[1]

In [ ]:
a[[0,2,3,5]]

In [ ]:
a[[0,2]]

In [ ]:
a = np.arange(1,21).reshape(5,4) 

In [ ]:
a

In [ ]:
 a[[1,2,3]]

In [ ]:
a[[2,4]]

In [ ]:
a[[0,3,3]]

In [ ]:
a[:,[0,2,3,]]

 ## Boolean Indexing 

In [ ]:
a[a%2]

In [ ]:
a


In [ ]:
a[a%2==1]

In [ ]:
f= np.random.randint(1,100,24).reshape(6,4)

In [ ]:
f

In [ ]:
f[f>50]

 ## Find number which  is greater than 50 

In [ ]:
f[f>50]

## find all number greater than 50 

In [ ]:
a[(a>50) & (a%2==0)]


In [ ]:
 a[~(a%7!=0)]

In [ ]:
a

In [ ]:
a = np.array([23,24,42,424,2,2,244244,42,42])

In [ ]:
a

In [ ]:
a.size


In [ ]:
a =a.reshape(3,3)

In [ ]:
a+a


In [ ]:
print(a+a)

In [ ]:
a

In [ ]:
a

In [ ]:
a+a

In [ ]:
f 

In [ ]:
a+f

In [ ]:
a = np.arange(6).reshape(2,3)
b= np.arange(6,12).reshape(3,2)

print(a)
print('\n')
print(b)
print('\n')
print(a+b)

In [ ]:
a


In [ ]:
a= np.arange(10)

In [ ]:
a


In [ ]:
a.mean()

## mathmathmetical function 

 # Sigmoid 

In [ ]:
def sigmoid(array) :
    return 1/(1+np.exp(-array)) 


In [ ]:
sigmoid(a)

 ## mean squared error 

In [ ]:
actual = np.random.randint(1,50,25) 
predicted = np.random.randint(1,50,25) 


In [ ]:
actual

In [ ]:
predicted

In [ ]:
def mse (actaul , predicted) :
     return np.mean((actual - predicted)**2) 

In [ ]:
mse(actual , predicted)

 # Working with missing value 

In [ ]:
a = np.array([1,2,3,4,5,6,6,np.nan ,23,4,3])

In [ ]:
a

In [ ]:
a.size

In [ ]:
a[~np.isnan(a)]

## ploting Graph Using Numpy 

In [ ]:
x =  np.linspace(-10,10,100)  #  -10 theke 10 porjonto 100 ta equil distance 

In [ ]:
x

In [ ]:
y = x

In [ ]:
y

In [ ]:
import matpolib as mt 

In [ ]:
pip install matpolib 

In [ ]:
sudo apt-get install python3-matplotlib


In [ ]:
import matplotlib.pyplot as plt


In [ ]:
plt.plot(x,y)

In [ ]:
 y=  x**2 +x

In [ ]:
plt.plot(x,y)

In [ ]:
 y = x * (np.log(x))

In [ ]:
 np.log(x)

In [ ]:
plt.plot(x,y)

In [ ]:
a =  np.array([12,232,332,4,42,424,24,23,32,23,32,34,42,424,2442,2442])

In [ ]:
a

In [ ]:
a.sort()

In [ ]:
a

In [ ]:
np.sort(a)

In [ ]:
a.size


In [ ]:
b= a.reshape(4,4)

In [ ]:
b

In [ ]:
np.sort(b )

In [ ]:
np.sort(b, axis=0)[::-1]

In [ ]:
a


In [ ]:
 np.append(a,200)

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis =1) 

In [ ]:
np.unique(a)

In [ ]:
a.size

 # expand Dims

# it helps to convert the array to different dimensions 

In [35]:
 a1 = np.expand_dims(a,axis=1)

In [36]:
a1

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [ ]:
a1

In [37]:
a1


array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [38]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
a = np.random.randint(1,100,20)

In [40]:
a

array([21, 62, 92,  2, 18, 27, 32, 64, 63, 51, 60, 46, 86, 66, 75, 48, 55,
       70, 15, 61])

In [41]:
np.where(a>50)

(array([ 1,  2,  7,  8,  9, 10, 12, 13, 14, 16, 17, 19]),)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [51]:
a[a>50] 

array([], dtype=int64)

In [52]:
a

array([21,  0,  0,  2, 18, 27, 32,  0,  0,  0,  0, 46,  0,  0,  0, 48,  0,
        0, 15,  0])

In [53]:
a

array([21,  0,  0,  2, 18, 27, 32,  0,  0,  0,  0, 46,  0,  0,  0, 48,  0,
        0, 15,  0])

In [54]:
a= np.random.randint(30,100,20)

In [55]:
a

array([85, 95, 60, 67, 40, 86, 67, 79, 75, 63, 38, 91, 95, 30, 30, 56, 61,
       62, 35, 50])

In [56]:
np.where(a%2==0,0,a)

array([85, 95,  0, 67,  0,  0, 67, 79, 75, 63,  0, 91, 95,  0,  0,  0, 61,
        0, 35,  0])

In [57]:
np.argmax(a)

1

In [58]:
a.sum()

1265

In [60]:
np.cumsum(a) 

array([  85,  180,  240,  307,  347,  433,  500,  579,  654,  717,  755,
        846,  941,  971, 1001, 1057, 1118, 1180, 1215, 1265])

In [61]:
a.prod()

4636423274995662848

In [62]:
np.cumprod(a)

array([                  85,                 8075,               484500,
                   32461500,           1298460000,         111667560000,
              7481726520000,      591056395080000,    44329229631000000,
        2792741466753000000, -4556288705643309696, -8793902591931046784,
       -5317262916519621760,  6502809167797311744, -7829909776885715456,
        4246910263429173248,   807109037245845504, -5299471911886233600,
       -1014076178922659840,  4636423274995662848])

In [63]:
 a

array([85, 95, 60, 67, 40, 86, 67, 79, 75, 63, 38, 91, 95, 30, 30, 56, 61,
       62, 35, 50])

In [69]:
np.percentile(a,50)

62.5

In [71]:
np.median(a)

62.5

In [73]:
np.corrcoef(a)

1.0

In [81]:
np.isin(95,30)

array(False)